import { TemplateButtons, TemplateCarrousel, TemplateList, TemplateMedia, TemplateOpenGraph, TemplateQuickReplies, TemplateReceipt, TemplateText } from './entities';
import { MediaAttachmentType } from '../../request/types';
export declare type TemplateType = 'text' | 'quick-replies' | 'button' | 'media' | 'list' | 'generic' | 'receipt' | 'open-graph';
export declare type AuthorizedTypes = TemplateType | 'stripe';
export declare type Template = TemplateText | TemplateQuickReplies | TemplateButtons | TemplateMedia | TemplateList | TemplateCarrousel | TemplateReceipt | TemplateOpenGraph;
export declare type TemplateFeedType = 'manual' | 'auto';
export declare type LayoutSize = 'small' | 'medium' | 'tall';
export declare type QuickReplyContentType = 'text' | 'location';
export declare type TemplateButtonType = 'postback' | 'url' | 'login' | 'call' | 'share';
export declare type TemplateDefaultActionType = 'postback' | 'url';
export declare type ButtonUrlWebviewType = 'tall' | 'compact' | 'full';
export declare type ButtonLoginService = 'google' | 'facebook';
export declare type MediaType = MediaAttachmentType | 'map' | 'calendar';
